CREATE TABLE USER
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(60) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    IS_SUPER BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID)
) ENGINE = InnoDB;
