INSERT INTO USER(USER_NAME,PASSWORD,IS_SUPER)
VALUES('admin','$2a$10$LYQjOujEanupmqKtA9USnO.P/rJl7QomserXzVpvNggJA/DHJcwuC',true);

INSERT INTO USER(USER_NAME,PASSWORD,IS_SUPER)
VALUES('registration','$2a$10$LYQjOujEanupmqKtA9USnO.P/rJl7QomserXzVpvNggJA/DHJcwuC',false);

INSERT INTO USER(USER_NAME,PASSWORD,IS_SUPER)
VALUES('consultant','$2a$10$LYQjOujEanupmqKtA9USnO.P/rJl7QomserXzVpvNggJA/DHJcwuC',false);

INSERT INTO USER(USER_NAME,PASSWORD,IS_SUPER)
VALUES('seller','$2a$10$LYQjOujEanupmqKtA9USnO.P/rJl7QomserXzVpvNggJA/DHJcwuC',false);

INSERT INTO USER(USER_NAME,PASSWORD,IS_SUPER)
VALUES('user','$2a$10$LYQjOujEanupmqKtA9USnO.P/rJl7QomserXzVpvNggJA/DHJcwuC',false);